local function run(msg, matches)
 if not is_momod(msg) then 
  return "For moderators only !"
 end
 if matches[1] then
  return "BLACK WOLF\NBLACK WOLF\NBLACK WOLF\NBLACK WOLF\NBLACK WOLF\NBLACK WOLF\NBLACK WOLF\NBLACK WOLF\NBLACK WOLF\NBLACK WOLF\NBLACK WOLF\NBLACK WOLF\NBLACK WOLF\NBLACK WOLF\NBLACK WOLF\NBLACK WOLF\NBLACK WOLF\NBLACK WOLF\NBLACK WOLF\NBLACK WOLF\NBLACK WOLF\NBLACK WOLF\NBLACK WOLF\NBLACK WOLF\NBLACK WOLF\NBLACK WOLF\NBLACK WOLF\NBLACK WOLF\NBLACK WOLF\NBLACK WOLF\NBLACK WOLF\NBLACK WOLF\NBLACK WOLF\NBLACK WOLF\NBLACK WOLF\NBLACK WOLF\NBLACK WOLF\NBLACK WOLF\NBLACK WOLF\NBLACK WOLF\NBLACK WOLF\NBLACK WOLF\NBLACK WOLF\NBLACK WOLF\NBLACK WOLF\NBLACK WOLF\NBLACK WOLF\NBLACK WOLF\NBLACK WOLF\NBLACK WOLF\NBLACK WOLF\NBLACK WOLF\NBLACK WOLF\NBLACK WOLF\NBLACK WOLF\NBLACK WOLF\NBLACK WOLF\NBLACK WOLF\NBLACK WOLF\NBLACK WOLF\NBLACK WOLF\NBLACK WOLF\NBLACK WOLF\NBLACK WOLF\NBLACK WOLF\NBLACK WOLF\NBLACK WOLF\NBLACK WOLF\NBLACK WOLF\NBLACK WOLF\NBLACK WOLF\NBLACK WOLF\NBLACK WOLF\NBLACK WOLF\NBLACK WOLF\NBLACK WOLF\NBLACK WOLF\NBLACK WOLF\NBLACK WOLF\NBLACK WOLF\NBLACK WOLF\NBLACK WOLF\NBLACK WOLF\NBLACK WOLF\NBLACK WOLF\NBLACK WOLF\NBLACK WOLF\NBLACK WOLF\NBLACK WOLF\NBLACK WOLF\NBLACK WOLF\NBLACK WOLF\NBLACK WOLF\NBLACK WOLF\NBLACK WOLF\NBLACK WOLF\NBLACK WOLF\NBLACK WOLF\NBLACK WOLF\NBLACK WOLF\NBLACK WOLF\NBLACK WOLF\NBLACK WOLF\NBLACK WOLF\NBLACK WOLF\NBLACK WOLF\NBLACK WOLF\NBLACK WOLF\NBLACK WOLF\NBLACK WOLF\NBLACK WOLF\NBLACK WOLF\NBLACK WOLF\NBLACK WOLF\NBLACK WOLF\NBLACK WOLF\NBLACK WOLF\NBLACK WOLF\NBLACK WOLF\NBLACK WOLF\NBLACK WOLF\NBLACK WOLF\NBLACK WOLF\NBLACK WOLF\NBLACK WOLF\NBLACK WOLF\NBLACK WOLF\NBLACK WOLF\NBLACK WOLF\NBLACK WOLF\NBLACK WOLF\NBLACK WOLF\NBLACK WOLF\NBLACK WOLF\N"
end
 return
end


return {
  description = "",
  usage = {""},
  patterns = {
    "^[!/]([Bb]lackwolf)";
    

  },
  run = run
}
