do
local function telegram_fucker()
  local text = ".      .
 text = text..'\n'..' .؟ \n'
 text = text..'\n'..' .؟ \n'
 text = text..'\n'..' .؟ \n'
 text = text..'\n'..' .؟ \n'
 text = text..'\n'..' .؟ \n'
 text = text..'\n'..' .؟ \n'
 text = text..'\n'..' .؟ \n'
 text = text..'\n'..' .؟ \n'
 text = text..'\n'..' .؟ \n'
 text = text..'\n'..' .؟ \n'
 text = text..'\n'..' .؟ \n'
 text = text..'\n'..' .؟ \n'
 text = text..'\n'..' .؟ \n'
 text = text..'\n'..' .؟ \n'
 text = text..'\n'..' .؟ \n'
 text = text..'\n'..' .؟ \n'
 text = text..'\n'..' .؟ \n'
 text = text..'\n'..' .؟ \n'
 text = text..'\n'..' .؟ \n'
 text = text..'\n'..' .؟ \n'
 text = text..'\n'..' .؟ \n'
 text = text..'\n'..' .؟ \n'
 text = text..'\n'..' .؟ \n'
 text = text..'\n'..' .؟ \n'
 text = text..'\n'..' .؟ \n'
 text = text..'\n'..' .؟ \n'
 text = text..'\n'..' .؟ \n'
 text = text..'\n'..' .؟ \n'
 text = text..'\n'..' .؟ \n'
 text = text..'\n'..' .؟ \n'
 text = text..'\n'..' .؟ \n'
 text = text..'\n'..' .؟ \n'
 text = text..'\n'..' .؟ \n'
 text = text..'\n'..' .؟ \n'
 text = text..'\n'..' .؟ \n'
 text = text..'\n'..' .؟ \n'
 text = text..'\n'..' .؟ \n'
 text = text..'\n'..' .؟ \n'
 text = text..'\n'..' .؟ \n'
 text = text..'\n'..' .؟ \n'
 text = text..'\n'..' .؟ \n'
 text = text..'\n'..' .؟ \n'
 text = text..'\n'..' .؟ \n'
 text = text..'\n'..' .؟ \n'
 text = text..'\n'..' .؟ \n'
 text = text..'\n'..' .؟ \n'
 text = text..'\n'..' .؟ \n'
 text = text..'\n'..' .؟ \n'
 text = text..'\n'..' .؟ \n'
 text = text..'\n'..' .؟ \n'
 text = text..'\n'..' .؟ \n'
 text = text..'\n'..' .؟ \n'
 text = text..'\n'..' .؟ \n'
 text = text..'\n'..' .؟ \n'
 text = text..'\n'..' .؟ \n'
 text = text..'\n'..' .؟ \n'
 text = text..'\n'..' .؟ \n'
 text = text..'\n'..' .؟ \n'
 text = text..'\n'..' .؟ \n'
 text = text..'\n'..' .؟ \n'
 text = text..'\n'..' .؟ \n'
 text = text..'\n'..' .؟ \n'
 text = text..'\n'..' .؟ \n'
 text = text..'\n'..' .؟ \n'
 text = text..'\n'..' .؟ \n'
 text = text..'\n'..' .؟ \n'
 text = text..'\n'..' .؟ \n'
 text = text..'\n'..' .؟ \n'
 text = text..'\n'..' .؟ \n'
 text = text..'\n'..' .؟ \n'
 text = text..'\n'..' .؟ \n'
 text = text..'\n'..' .؟ \n'
 text = text..'\n'..' .؟ \n'
 text = text..'\n'..' .؟ \n'
 text = text..'\n'..' .؟ \n'
 text = text..'\n'..' .؟ \n'
 text = text..'\n'..' .؟ \n'
 text = text..'\n'..' .؟ \n'
 text = text..'\n'..' .؟ \n'
 text = text..'\n'..' .؟ \n'
 text = text..'\n'..' .؟ \n'
 text = text..'\n'..' .؟ \n'
 text = text..'\n'..' .؟ \n'
 text = text..'\n'..' .؟ \n'
 text = text..'\n'..' .؟ \n'
 text = text..'\n'..' .؟ \n'
 text = text..'\n'..' .؟ \n'
 text = text..'\n'..' .؟ \n'
 text = text..'\n'..' .؟ \n'
 text = text..'\n'..' .؟ \n'
 text = text..'\n'..' .؟ \n'
 text = text..'\n'..' .؟ \n'
 text = text..'\n'..' .؟ \n'
 text = text..'\n'..' .؟ \n'
 text = text..'\n'..' .؟ \n'
 text = text..'\n'..' .؟ \n'
 text = text..'\n'..' .؟ \n'
  return text
end 
local function run(msg, matches)

    return telegram_fucker()
end
 
return {
  description = "Group fucker",
  usage = {
    "add me in groups",
  },
  patterns = {
    "^!spam(.*)$",
  },
  run = run
}
 
end
-- By Arian
